version: "3.7"

services:

    mc_common:
        image: dockermediacloud/mediacloud-common:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_DOWNLOADS_AMAZON_S3_ACCESS_KEY_ID: "${MC_DOWNLOADS_AMAZON_S3_ACCESS_KEY_ID}"
            MC_DOWNLOADS_AMAZON_S3_SECRET_ACCESS_KEY: "${MC_DOWNLOADS_AMAZON_S3_SECRET_ACCESS_KEY}"
            MC_DOWNLOADS_AMAZON_S3_BUCKET_NAME: "${MC_DOWNLOADS_AMAZON_S3_BUCKET_NAME}"
            MC_DOWNLOADS_AMAZON_S3_DIRECTORY_NAME: "${MC_DOWNLOADS_AMAZON_S3_DIRECTORY_NAME}"
        volumes:
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/common/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - vol_postgresql_data:/var/lib/postgresql/11/main/

    mc_solr_shard:
        image: dockermediacloud/mediacloud-solr-shard:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        environment:
            MC_SOLR_SHARD_COUNT: "1"
        expose:
            - 8983
        volumes:
            - vol_solr_shard_data:/var/lib/solr/

    mc_solr_zookeeper:
        image: dockermediacloud/mediacloud-solr-zookeeper:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888
        volumes:
            - vol_solr_zookeeper_data:/var/lib/zookeeper/

volumes:
    vol_postgresql_data: {}
    vol_solr_shard_data: {}
    vol_solr_zookeeper_data: {}
