---

- name: Install Apache
  apt:
    name:
      - apache2
      - libapache2-mod-fcgid
    state: present
    install_recommends: false
  become: true
  become_user: root
  tags:
    - apache2-fcgi
