version: "3.7"

services:

    mc_cliff_update_story_tags:
        image: dockermediacloud/mediacloud-cliff-update-story-tags:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_CLIFF_VERSION_TAG: "cliff_clavin_v2.4.1"
            MC_CLIFF_GEONAMES_TAG_SET: "cliff_geonames"
            MC_CLIFF_ORGANIZATIONS_TAG_SET: "cliff_organizations"
            MC_CLIFF_PEOPLE_TAG_SET: "cliff_people"
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/cliff-update-story-tags/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../cliff-base/src/
              target: /opt/mediacloud/src/cliff-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432
