version: "3.7"

services:

    mc_crawler_fetcher:
        image: dockermediacloud/mediacloud-crawler-fetcher:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_UNIVISION_CLIENT_ID: "${MC_UNIVISION_CLIENT_ID}"
            MC_UNIVISION_CLIENT_SECRET: "${MC_UNIVISION_CLIENT_SECRET}"
            # Used by Univision test only
            MC_UNIVISION_TEST_URL: "${MC_UNIVISION_TEST_URL}"
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/crawler-fetcher/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_postgresql_pgbouncer
            # Fetcher's test will try to add downloaded downloads to extractor's queue
            - mc_rabbitmq_server

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    mc_rabbitmq_server:
        image: dockermediacloud/mediacloud-rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
