version: 0.2

phases:

  install:
    runtime-versions:
      docker: 18
    commands:
      # Upgrade docker-compose
      - pip3 install --quiet --upgrade docker-compose && docker-compose version
      # Install PyYAML for docker-compose.yml validation
      - pip3 install --quiet PyYAML
      # Try to pull all the images that are about to be built from Docker Hub to be
      # used for cache.
      #
      # Don't stop on a single failure because the image might not exist or a
      # network error might have happened.
      - ./build_tools/print_pull_commands.py | bash || true

  pre_build:
    commands:
      # Build all images
      - ./build_tools/print_build_commands.py | bash

  build:
    commands:
      # Run all test files in all containers
      - ./build_tools/print_run_all_tests_commands.py | parallel --jobs 4 --group

  post_build:
    commands:
      # Log in to Docker Hub
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      # Push all images to Docker Hub
      - ./build_tools/print_push_commands.py | bash
