stages:
- stage: pull
  jobs:
  - job: docker_pull
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: echo docker pull
- stage: build
  dependsOn: pull
  jobs:
  - job: docker_build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: echo docker build
- stage: test_chunk_1
  dependsOn: pull
  jobs:
  - job: docker_test_chunk_1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: echo docker test chunk 1
- stage: test_chunk_2
  dependsOn: pull
  jobs:
  - job: docker_test_chunk_2
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: echo docker test chunk 2
- stage: test_chunk_3
  dependsOn: pull
  jobs:
  - job: docker_test_chunk_3
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: echo docker test chunk 3
- stage: test_chunk_4
  dependsOn: pull
  jobs:
  - job: docker_test_chunk_4
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: echo docker test chunk 4
- stage: push
  dependsOn:
  - test_chunk_1
  - test_chunk_2
  - test_chunk_3
  - test_chunk_4
  jobs:
  - job: docker_push
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: echo docker push
