#
# Docker Swarm publishes ports on all hosts and doesn't support "ip_to_bind_to:host_port:container_port" syntax, and UFW 

# Webapp is only accessible through Nginx proxy:
- name: Deny connections to webapp's unsecured HTTP server
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 8082
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables

- name: Deny connections to unsecured CLIFF annotator
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 8090
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables

- name: Deny connections to unsecured NYTLabels annotator
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 8091
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables

- name: Deny connections to Munin HTTP server
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 4948
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables

- name: Deny connections to pgAdmin
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 5050
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables

- name: Deny connections to Solr's webapp proxy
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 8983
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables

- name: Deny connections to Portainer
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 9000
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables

- name: Deny connections to RabbitMQ's webapp proxy
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 15672
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables

- name: Deny connections to ELK Kibana
  iptables:
    # Insert before RETURN
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    destination_port: 5601
    jump: DROP
  become: true
  become_user: root
  tags:
    - docker
    - iptables
