---

- name: Include variables
  include_vars: ../vars/main-{{ ansible_distribution }}.yml
  tags:
    - timezone

- name: Install tzdata
  apt:
    name: tzdata
    state: present
  become: true
  become_user: root
  tags:
    - timezone

- name: Write timezone to /etc/timezone
  copy:
    content: "{{ mediacloud_timezone }}"
    dest: /etc/timezone
  notify:
    - restart cron  # for cron jobs to fire at the right time
  become: true
  become_user: root
  tags:
    - timezone

- name: Remove /etc/localtime
  file:
    path: /etc/localtime
    state: absent
  notify:
    - restart cron
  become: true
  become_user: root
  tags:
    - timezone

- name: Symlink timezone to /etc/localtime
  file:
    src: "/usr/share/zoneinfo/{{ mediacloud_timezone }}"
    dest: /etc/localtime
    state: link
  notify:
    - restart cron
  become: true
  become_user: root
  tags:
    - timezone

- name: Reconfigure timezones
  command: dpkg-reconfigure -f noninteractive tzdata
  notify:
    - restart cron
  become: true
  become_user: root
  tags:
    - timezone
