postgresql_psql_become: false
postgresql_psql_become_user: null
postgresql_psql_login_user: "{{ mediacloud_user }}"

# Directory with postgresql.conf
postgresql_conf_dir: "/usr/local/var/postgres/"

# Should we sudo to create conf.d directory
postgresql_conf_become: false

# User, group for the conf.d directory and its contents
postgresql_conf_user: "{{ ansible_user_id }}"
postgresql_conf_group: "admin"
