version: "3.7"

services:

    mc_topics_base:
        image: dockermediacloud/mediacloud-topics-base:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        volumes:
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/topics-base/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_migrate_schema
            - mc_rabbitmq_server
            # For test_generate_story:
            - mc_extract_and_vector

    mc_extract_and_vector:
        image: dockermediacloud/mediacloud-extract-and-vector:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer
            - mc_extract_article_from_page

    mc_extract_article_from_page:
        image: dockermediacloud/mediacloud-extract-article-from-page:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 80

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    mc_rabbitmq_server:
        image: dockermediacloud/mediacloud-rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M
