version: "3.7"

services:

    topics-base:
        image: dockermediacloud/topics-base:latest
        stop_signal: SIGKILL
        env_file: ./../common/common.env.dist
        volumes:
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/topics-base/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer
            - rabbitmq-server
            # For test_generate_story:
            - extract-and-vector

    extract-and-vector:
        image: dockermediacloud/extract-and-vector:latest
        env_file: ./../common/common.env.dist
        stop_signal: SIGKILL
        depends_on:
            - postgresql-pgbouncer
            - extract-article-from-page

    extract-article-from-page:
        image: dockermediacloud/extract-article-from-page:latest
        env_file: ./../common/common.env.dist
        stop_signal: SIGKILL
        expose:
            - 8080

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        stop_signal: SIGKILL
        expose:
            - 5432

    rabbitmq-server:
        image: dockermediacloud/rabbitmq-server:latest
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
