version: "3.7"

services:

    mc_nytlabels_update_story_tags:
        image: dockermediacloud/mediacloud-nytlabels-update-story-tags:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_NYTLABELS_VERSION_TAG: "nyt_labeller_v1.0.0"
            MC_NYTLABELS_TAG_SET: "nyt_labels"
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/nytlabels-update-story-tags/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../nytlabels-base/src/
              target: /opt/mediacloud/src/nytlabels-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_migrate_schema

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - vol_postgresql_data:/var/lib/postgresql/11/main/

volumes:
    vol_postgresql_data: {}
