version: "3.7"

services:

    # Service to use for testing the mail service
    #
    # Usage:
    #
    #     - host$ ./dev/run.py mail-postfix-server bash
    #     - (new terminal window) host$ docker ps
    #     - find container with name ending in 'mail-postfix-server-actual_1'
    #     - host$ docker exec -it some_string_mail-postfix-server-actual_1 bash
    #     - mail-postfix-server-actual_1_container$ ./postfix.sh
    #     - open new terminal window on your host machine
    #     - host$ docker exec -it some_string_mail-postfix-server-actual_1 bash
    #     - follow instructions at URL below to create a test mail.txt file and send to your email address from the container
    #     https://clients.javapipe.com/knowledgebase/132/How-to-Test-Sendmail-From-Command-Line-on-Linux.html
    #
    mail-postfix-server:
        image: gcr.io/mcback/common:latest
        init: true
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mail-postfix-server-actual

    # Actual mail server, operating under "mail-postfix-server" alias
    mail-postfix-server-actual:
        image: gcr.io/mcback/mail-postfix-server:latest
        init: true
        stop_signal: SIGKILL
        # "docker exec" into a container and run Postfix manually (./postfix.sh):
        command: sleep infinity
        # To be able to set /proc/sys/kernel/yama/ptrace_scope:
        privileged: true
        environment:
            MC_MAIL_POSTFIX_FQDN: "mail.testmediacloud.ml"
        depends_on:
            - mail-opendkim-server
        networks:
            default:
                aliases:
                    - mail-postfix-server

    mail-opendkim-server:
        image: gcr.io/mcback/mail-opendkim-server:latest
        init: true
        environment:
            MC_MAIL_OPENDKIM_DOMAIN: "testmediacloud.ml"
        expose:
            - "12301"
        volumes:
            - type: bind
              source: ./../mail-opendkim-server/etc/opendkim.conf
              target: /etc/opendkim.conf
            - type: bind
              source: ./../mail-opendkim-server/etc/opendkim/
              target: /etc/opendkim/

networks:
    default:
        attachable: true
        ipam:
            driver: default
            config:
                # Use same subnet as in production
                - subnet: "10.1.0.0/16"
