- name: Restart Journald
  # Send HUP signal for the service to preserve old logs
  shell: "killall -USR1 systemd-journald"
  become: true
  become_user: root
  tags:
    - docker
    - journald

- name: Restart Docker
  service:
    name: docker
    state: restarted
  become: true
  become_user: root
  tags:
    - docker
    - dockerd
