version: "3.7"

services:

    mc_topics_mine:
        image: dockermediacloud/mediacloud-topics-mine:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_CRIMSON_HEXAGON_API_KEY: "${MC_CRIMSON_HEXAGON_API_KEY}"
        expose:
            # test_tm_mine.t's test HTTP servers:
            - 8890
            - 8891
            - 8892
            - 8893
            - 8894
            - 8895
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/topics-mine/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../topics-base/src/
              target: /opt/mediacloud/src/topics-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_migrate_schema
            - mc_rabbitmq_server
            - mc_topics_fetch_link
            - mc_topics_extract_story_links
            # 1) test_topics_mine.t calls mc_topics_fetch_link
            # 2) mc_topics_fetch_link calls _try_fetch_topic_url()
            # 3) _try_fetch_topic_url() calls generate_story()
            # 4) generate_story() calls _extract_story()
            # 5) _extract_story() runs a remote extraction job
            - mc_extract_and_vector

    mc_extract_and_vector:
        image: dockermediacloud/mediacloud-extract-and-vector:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer
            - mc_extract_article_from_page

    mc_extract_article_from_page:
        image: dockermediacloud/mediacloud-extract-article-from-page:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 80

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    mc_rabbitmq_server:
        image: dockermediacloud/mediacloud-rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M

    mc_topics_fetch_link:
        image: dockermediacloud/mediacloud-topics-fetch-link:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL

    mc_topics_extract_story_links:
        image: dockermediacloud/mediacloud-topics-extract-story-links:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
