version: "3.7"

services:

    mc_topics_fetch_twitter_urls:
        image: dockermediacloud/mediacloud-topics-fetch-twitter-urls:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_TWITTER_CONSUMER_KEY: "${MC_TWITTER_CONSUMER_KEY}"
            MC_TWITTER_CONSUMER_SECRET: "${MC_TWITTER_CONSUMER_SECRET}"
            MC_TWITTER_ACCESS_TOKEN: "${MC_TWITTER_ACCESS_TOKEN}"
            MC_TWITTER_ACCESS_TOKEN_SECRET: "${MC_TWITTER_ACCESS_TOKEN_SECRET}"
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/topics-fetch-twitter-urls/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../topics-base/src/
              target: /opt/mediacloud/src/topics-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_migrate_schema
            # 1) _add_tweet_story() calls generate_story()
            # 2) generate_story() calls _extract_story()
            # 3) _extract_story() runs a remote extraction job
            - mc_extract_and_vector
            - mc_rabbitmq_server

    mc_extract_and_vector:
        image: dockermediacloud/mediacloud-extract-and-vector:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer
            - mc_extract_article_from_page

    mc_extract_article_from_page:
        image: dockermediacloud/mediacloud-extract-article-from-page:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 80

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - vol_postgresql_data:/var/lib/postgresql/11/main/

    mc_rabbitmq_server:
        image: dockermediacloud/mediacloud-rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
        volumes:
            - vol_rabbitmq_data:/var/lib/rabbitmq/

volumes:
    vol_postgresql_data: {}
    vol_rabbitmq_data: {}
