version: "3.7"

services:

    mc_topics_extract_story_links:
        image: dockermediacloud/mediacloud-topics-extract-story-links:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/topics-extract-story-links/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            # test_get_links_from_html() uses html-strip/strip.html from common's test data
            - type: bind
              source: ../common/tests/data/
              target: /opt/mediacloud/tests/data/
            - type: bind
              source: ./../topics-base/src/
              target: /opt/mediacloud/src/topics-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_migrate_schema
            # Uses extractor HTTP service directly to get raw extracted HTML:
            - mc_extract_article_from_page

    mc_extract_article_from_page:
        image: dockermediacloud/mediacloud-extract-article-from-page:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 80

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - vol_postgresql_data:/var/lib/postgresql/11/main/

volumes:
    vol_postgresql_data: {}
