version: "3.7"

services:

    proxy-httpd:
        image: dockermediacloud/proxy-httpd:latest
        environment:
            MC_PROXY_HTTPD_AUTH_USERS: "${MC_PROXY_HTTPD_AUTH_USERS}"
        ports:
            # Expose to host for debugging
            - "80:8080"
            - "4443:443"
        volumes:
            - type: bind
              source: ./nginx/
              target: /etc/nginx/
            # Shared with proxy-cron-certbot:
            - vol_proxy_ssl_certs:/etc/letsencrypt/
        depends_on:
            - proxy-cron-certbot
            - webapp-httpd
            - munin-httpd
            - portainer
            - solr-shard
            - rabbitmq-server

    proxy-cron-certbot:
        image: dockermediacloud/proxy-cron-certbot:latest
        environment:
            MC_PROXY_CERTBOT_DOMAIN: "testmediacloud.ml"
            MC_PROXY_CERTBOT_LETSENCRYPT_EMAIL: "linas@media.mit.edu"
            MC_PROXY_CERTBOT_CLOUDFLARE_EMAIL: "${MC_PROXY_CERTBOT_CLOUDFLARE_EMAIL}"
            MC_PROXY_CERTBOT_CLOUDFLARE_GLOBAL_API_KEY: "${MC_PROXY_CERTBOT_CLOUDFLARE_GLOBAL_API_KEY}"
        volumes:
            # Shared with proxy-httpd:
            - vol_proxy_ssl_certs:/etc/letsencrypt/

    webapp-httpd:
        image: dockermediacloud/webapp-httpd:latest
        stop_signal: SIGKILL
        expose:
            - "80"
        depends_on:
            - webapp-api

    webapp-api:
        image: dockermediacloud/webapp-api:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        expose:
            - "9090"
        # Here and elsewhere, don't start any subservices via "depends_on"
        # because we need to only make sure that /status page works

    munin-httpd:
        image: dockermediacloud/munin-httpd:latest
        stop_signal: SIGKILL
        expose:
            - "8080"

    portainer:
       image: portainer/portainer:1.20.2
       expose:
           - "9000"

    solr-shard:
        image: dockermediacloud/solr-shard:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        environment:
            MC_SOLR_SHARD_COUNT: "1"
        expose:
            - 8983
        depends_on:
            - solr-zookeeper

    solr-zookeeper:
        image: dockermediacloud/solr-zookeeper:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888

    rabbitmq-server:
        image: dockermediacloud/rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672

volumes:
    vol_proxy_ssl_certs: {}
