version: "3.7"

services:

    mc_import_stories_scrapehtml:
        image: dockermediacloud/mediacloud-import-stories-scrapehtml:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        volumes:
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/import-stories-scrapehtml/
            - type: bind
              source: ./../import-stories-base/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../import-stories-base/src/
              target: /opt/mediacloud/src/import-stories-base/
            - type: bind
              source: ./../extract-and-vector/src/
              target: /opt/mediacloud/src/extract-and-vector/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432
