version: "3.7"

services:

    postgresql-pgadmin:
        image: dockermediacloud/postgresql-pgadmin:latest
        stop_signal: SIGKILL
        ports:
            # Expose to host for debugging
            - "5050:5050"
        volumes:
            - type: bind
              source: ./pgadmin.sh
              target: /pgadmin.sh
        depends_on:
            - postgresql-pgbouncer

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        stop_signal: SIGKILL
        expose:
            - 5432
