version: "3.7"

services:

    mc_import_solr_data_for_testing:
        image: dockermediacloud/mediacloud-import-solr-data-for-testing:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_SOLR_IMPORT_JOBS: 1
            MC_SOLR_IMPORT_MAX_QUEUED_STORIES: 100000
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/import-solr-data-for-testing/
            - type: bind
              source: ./../import-solr-data/src/
              target: /opt/mediacloud/src/import-solr-data/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - mc_postgresql_pgbouncer
            - mc_solr_shard
            - mc_rabbitmq_server

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    mc_solr_shard:
        image: dockermediacloud/mediacloud-solr-shard:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        environment:
            MC_SOLR_SHARD_COUNT: "1"
        expose:
            - 8983
        depends_on:
            - mc_solr_zookeeper

    mc_solr_zookeeper:
        image: dockermediacloud/mediacloud-solr-zookeeper:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888

    mc_rabbitmq_server:
        image: dockermediacloud/mediacloud-rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
