version: "3.7"

services:

    mc_common:
        image: dockermediacloud/mediacloud-common:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_DOWNLOADS_AMAZON_S3_ACCESS_KEY_ID: "${MC_DOWNLOADS_AMAZON_S3_ACCESS_KEY_ID}"
            MC_DOWNLOADS_AMAZON_S3_SECRET_ACCESS_KEY: "${MC_DOWNLOADS_AMAZON_S3_SECRET_ACCESS_KEY}"
            MC_DOWNLOADS_AMAZON_S3_BUCKET_NAME: "${MC_DOWNLOADS_AMAZON_S3_BUCKET_NAME}"
            MC_DOWNLOADS_AMAZON_S3_DIRECTORY_NAME: "${MC_DOWNLOADS_AMAZON_S3_DIRECTORY_NAME}"
        volumes:
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/common/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
        depends_on:
            - mc_migrate_schema
            - mc_solr_shard
            - mc_import_solr_data_for_testing
            - mc_rabbitmq_server

    mc_import_solr_data_for_testing:
        image: dockermediacloud/mediacloud-import-solr-data-for-testing:latest
        env_file: ./../global.env.dist
        environment:
            MC_SOLR_IMPORT_JOBS: 1
            MC_SOLR_IMPORT_MAX_QUEUED_STORIES: 100000
        stop_signal: SIGKILL
        depends_on:
            - mc_migrate_schema
            - mc_solr_shard

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    mc_solr_shard:
        image: dockermediacloud/mediacloud-solr-shard:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        environment:
            MC_SOLR_SHARD_COUNT: "1"
        expose:
            - 8983
        depends_on:
            - mc_solr_zookeeper
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M

    mc_solr_zookeeper:
        image: dockermediacloud/mediacloud-solr-zookeeper:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M

    mc_rabbitmq_server:
        image: dockermediacloud/mediacloud-rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M
