version: "3.7"

services:

    mc_munin_cron:
        image: dockermediacloud/mediacloud-munin-cron:latest
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./munin-conf.d/
              target: /etc/munin/munin-conf.d/
        depends_on:
            - mc_munin_node

    mc_munin_node:
        image: dockermediacloud/mediacloud-munin-node:latest
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./../munin-node/plugins/
              target: /etc/munin/plugins/
        depends_on:
            # Monitors a bunch of stuff on PostgreSQL
            - mc_migrate_schema
            # Monitors stuff on Solr too
            - mc_solr_shard

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    mc_solr_shard:
        image: dockermediacloud/mediacloud-solr-shard:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        environment:
            MC_SOLR_SHARD_COUNT: "1"
        expose:
            - 8983
        depends_on:
            - mc_solr_zookeeper

    mc_solr_zookeeper:
        image: dockermediacloud/mediacloud-solr-zookeeper:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888
