---

- name: Start and enable PostgreSQL
  command: brew services start postgresql
  args:
    creates: "{{ mediacloud_home }}/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
  tags:
    - postgresql-server
