version: "3.7"

services:

    mc_cron_generate_media_health:
        image: dockermediacloud/mediacloud-cron-generate-media-health:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/cron-generate-media-health/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/

    mc_migrate_schema:
        image: dockermediacloud/mediacloud-migrate-schema:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        logging:
            driver: none

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        logging:
            driver: none
        expose:
            - 6432

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        logging:
            driver: none
        expose:
            - 5432
        volumes:
            - vol_postgresql_data:/var/lib/postgresql/11/main/

volumes:
    vol_postgresql_data: {}
