#
# Deploy code updates
#

- name: Deploy code updates
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  pre_tasks:
    - name: Include pre-tasks
      include_tasks: pre-tasks.yml
      tags: always
  roles:
    - deploy
