#
# Pre-install Media Cloud dependencies for the LXD image used by Travis
#

- name: Set up host for running Media Cloud
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  pre_tasks:
    - name: Include pre-tasks
      include_tasks: pre-tasks.yml
      tags: always
  roles:
    - update-packages
    - common
    - locale
    - timezone
    - system-packages
    - postgresql-server
    - pam-limits
    - python-dependencies
    - perlbrew
    - perl-dependencies
