# All hosts
all:

  hosts:

    # Localhost
    "localhost":
     ansible_connection: local

    # Sample hosts to deploy to
    "mcsample1":
      ansible_host: "mcsample1.media.mit.edu"
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "~/.ssh/mcsample"

      # Network interface the IP of which will be advertised to the rest of the swarm
      docker_swarm_advertise_interface: "eth0"

    "mcsample2":
      ansible_host: "mcsample2.media.mit.edu"
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "~/.ssh/mcsample"

      docker_swarm_advertise_interface: "eth0"

    "mcsample3":
      ansible_host: "mcsample3.media.mit.edu"
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "~/.ssh/mcsample"

      docker_swarm_advertise_interface: "eth0"

# Group of 1-3 hosts that will serve as swarm managers
# (for testing, use a single manager; for production, define 3 managers)
docker_swarm_managers:

  hosts:
    "mcsample1":

# Group of 1-3 hosts that will serve as swarm workers
# (hosts from the manager group don't have to be readded here)
docker_swarm_workers:

  hosts:
    "mcsample2":
    "mcsample3":
