---

- name: Add mecab-ipadic-neologd APT repository
  apt_repository:
    repo: "deb https://dl.bintray.com/pypt/mecab-ipadic-neologd-deb {{ ansible_lsb.codename | lower }} main"
    state: present
    filename: "bintray-pypt-mecab-ipadic-neologd"
    update_cache: yes
  become: true
  become_user: root
  tags:
    - system-packages

- name: Install system packages
  apt:
    name: "{{item}}"
    state: present
    install_recommends: false
  with_items:
    - cpanminus
    - expat
    - g++
    - gawk
    - gcc
    - graphviz
    - graphviz-dev
    - hunspell
    - libexpat1-dev
    - libhunspell-dev
    - libmecab-dev
    - libgraphviz-dev
    - libre2-dev
    - libtidy-dev
    - libxml2-dev
    - libxml2-dev
    - libxslt1-dbg
    - libxslt1-dev
    - libxslt1.1
    - libyaml-dev
    - libssl-dev  # OpenSSL headers
    - make
    - mecab
    - mecab-ipadic-neologd
    - openjdk-8-jdk
    - pkg-config
    - unzip
  become: true
  become_user: root
  tags:
    - system-packages

- name: Use Java 8 by default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  become: true
  become_user: root
  tags:
    - system-packages
