---

- name: Add RabbitMQ GPG key
  apt_key:
    url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
    state: present
  become: true
  become_user: root
  tags:
    - system-packages

# apt_key doesn't work for whatever reason
- name: Add Bintray.com GPG key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
  changed_when: false
  become: true
  become_user: root
  tags:
    - system-packages

- name: Add RabbitMQ APT repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    state: present
    filename: rabbitmq
    update_cache: yes
  become: true
  become_user: root
  tags:
    - system-packages

- name: Add mecab-ipadic-neologd APT repository
  apt_repository:
    repo: "deb https://dl.bintray.com/pypt/mecab-ipadic-neologd-deb xenial main"
    state: present
    filename: "bintray-pypt-mecab-ipadic-neologd"
    update_cache: yes
  become: true
  become_user: root
  tags:
    - system-packages    

- name: Install system packages
  apt:
    name: "{{item}}"
    state: present
    install_recommends: false
  with_items:
    - curl
    - build-essential
    - ca-certificates
    - cpanminus
    - curl
    - expat
    - g++
    - gawk
    - gcc
    - graphviz
    - graphviz-dev
    - hunspell
    - libexpat1-dev
    - libmecab-dev
    - libgraphviz-dev
    - libtidy-dev
    - libxml2-dev
    - libxml2-dev
    - libxslt1-dbg
    - libxslt1-dev
    - libxslt1.1
    - libyaml-dev
    - libssl-dev  # OpenSSL headers
    - logrotate
    - make
    - mecab
    - mecab-ipadic-neologd
    - netcat
    - openjdk-8-jdk
    - python-pip
    - python2.7
    - python2.7-dev
    - "python{{ python_version }}"
    - "python{{ python_version }}-dev"
    - rabbitmq-server
    - unzip
  become: true
  become_user: root
  tags:
    - system-packages

- name: Remove obsolete system packages
  apt:
    name: "{{item}}"
    state: absent
    install_recommends: false
  with_items:
    - supervisor
  become: true
  become_user: root
  tags:
    - system-packages

- name: Stop and disable system RabbitMQ
  service:
    name: rabbitmq-server
    enabled: no
    state: stopped
  become: true
  become_user: root
  tags:
    - system-packages

- name: Use Java 8 by default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  become: true
  become_user: root
  tags:
    - system-packages
