- name: Include variables
  include_vars: ../vars/main-{{ ansible_distribution }}.yml
  tags:
    - system-packages

- name: Include tasks
  include_tasks: main-{{ ansible_distribution }}.yml
  tags:
    - system-packages

- name: Test if MeCab is of the correct version
  command: "mecab-config --version"
  ignore_errors: true
  changed_when: false
  register: mecab_current_version
  tags:
    - system-packages

- name: Ensure that MeCab is of the correct version
  assert:
    that:
      - mecab_current_version.stdout is version_compare(mecab_min_version, '>=')
  tags:
    - system-packages
