version: "3.7"

services:

    mc_cron_print_long_running_job_states:
        image: dockermediacloud/mediacloud-cron-print-long-running-job-states:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432
