---

- name: Add MAILTO environment variable
  cron:
    name: MAILTO
    env: true
    value: "{{ crontab_mailto | join(',') }}"
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - crontab

- name: Add HOME environment variable
  cron:
    name: HOME
    env: true
    value: "{{ mediacloud_home }}"
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - crontab

- name: Add SHELL environment variable
  cron:
    name: SHELL
    env: true
    value: "/bin/bash"
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - crontab

- name: Add PATH environment variable
  cron:
    name: PATH
    env: true
    value: "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - crontab

- name: Start Supervisor on reboot
  cron:
    name: "supervisor"
    special_time: reboot
    job: "{{ mediacloud_root }}/supervisor/supervisord.sh"
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - crontab

- name: Add Solr import script
  cron:
    name: "import_solr_data"
    disabled: true  # Temporarily disabled because it has been started manually on mcquery1
    minute: "57"
    job: >
      nice -n {{ crontab_import_solr_data_nice }}
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/script/import_solr_data.pl
      --delta
      --jobs {{ crontab_import_solr_data_jobs }}
      &> {{ crontab_import_solr_data_log_path }}
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab

- name: Add generate media health script
  cron:
    name: "generate_media_health"
    minute: "32"
    hour: "2"
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/script/generate_media_health.pl
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab

- name: Add rotate Supervisor logs script
  cron:
    name: "rotate_supervisor_logs"
    minute: "58"
    hour: "14"
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/tools/supervisor/rotate_supervisor_logs.py
      &> {{ crontab_rotate_supervisor_logs_log_path }}
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - crontab

- name: Add rotate HTTP request log script
  cron:
    name: "rotate_http_request_log"
    minute: "10"
    hour: "14"
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/tools/web/rotate_http_request_log.py
      &> {{ crontab_rotate_http_request_log_log_path }}
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - crontab

# Make sure that the following two commands are being run at more or less
# opposite times of day because one of them initializes rescraping and the
# other reports status of the last rescrape:

- name: Add rescrape due media script
  cron:
    name: "rescrape_due_media"
    minute: "0"
    hour: "3"
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/script/rescrape_due_media.pl
      &> {{ crontab_rescrape_due_media_log_path }}
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab

- name: Add rescraping changes script
  cron:
    name: "rescraping_changes"
    disabled: true  # Temporarily disabled by Hal "to make dump work"
    minute: "0"
    hour: "14"
    job: >
      psql -c "SELECT rescraping_changes(); SELECT update_feeds_from_yesterday()" 2>&1
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab

- name: Add generate daily user summary script
  cron:
    name: "generate_daily_user_summary"
    minute: "34"
    hour: "4"
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/script/generate_user_summary.pl
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab

- name: Add generate weekly user summary script
  cron:
    name: "generate_weekly_user_summary"
    minute: "22"
    hour: "5"
    weekday: "sun"

    # Report will be sent to MAILTO
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/script/generate_user_summary.pl
      --new 7
      --activity 7
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab

- name: Add refresh stats script
  cron:
    name: "refresh_mediacloud_stats"
    minute: "46"
    hour: "3"

    # Report will be sent to MAILTO
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/script/refresh_mediacloud_stats.pl
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab

- name: Add set media tags script
  cron:
    name: "set_media_tags"
    minute: "16"
    hour: "2"

    # Report will be sent to MAILTO
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/script/set_media_tags.pl
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab

- name: Generate daily rss dump
  cron:
    name: "generate_daily_rss_dumps"
    minute: "06"
    hour: "1"

    # Report will be sent to MAILTO
    job: >
      {{ mediacloud_root }}/script/run_in_env.sh
      {{ mediacloud_root }}/script/mediawords_generate_daily_rss_dumps.pl
  become: true
  become_user: "{{ mediacloud_user }}"
  when: "'core_services' in group_names"  # only for hosts in 'core_services' group
  tags:
    - crontab
