stages:

- stage: pull_build_push
  jobs:
  - job: pull_build_push
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: template-install-utils.yml
      - template: template-install-docker.yml
      - template: template-pull-images.yml
      - template: template-build-images.yml
      - template: template-push-images.yml

- stage: run_tests
  jobs:

  - job: run_tests_chunk_1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: template-install-utils.yml
      - template: template-install-docker.yml
      - template: template-pull-images.yml
      - template: template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_aa"

  - job: run_tests_chunk_2
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: template-install-utils.yml
      - template: template-install-docker.yml
      - template: template-pull-images.yml
      - template: template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_ab"

  - job: run_tests_chunk_3
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: template-install-utils.yml
      - template: template-install-docker.yml
      - template: template-pull-images.yml
      - template: template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_ac"

  - job: run_tests_chunk_4
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: template-install-utils.yml
      - template: template-install-docker.yml
      - template: template-pull-images.yml
      - template: template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_ad"

  - job: run_tests_chunk_5
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: template-install-utils.yml
      - template: template-install-docker.yml
      - template: template-pull-images.yml
      - template: template-split-tests-into-chunks.yml
        parameters:
          test_chunk_count: 5
      - template: template-run-chunk-tests.yml
        parameters:
          test_chunk_filename: "tests_chunk_ae"
