steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.7"
    addToPath: true

- script: sudo apt-get -y install parallel
  displayName: Install parallels

# Install PyYAML for docker-compose.yml validation
- script: sudo pip3 install PyYAML
  displayName: Install PyYAML
