steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.7"
    addToPath: true

# Install dependencies for python3-cryptography and parallel utility
- script: sudo apt-get -y install libssl-dev libffi-dev parallel

# Install PyYAML for docker-compose.yml validation
- script: sudo pip3 install PyYAML
