name: Pull, build, push, test

on: [push]

jobs:

  pull_build_push:

    name: Pull, build, push
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:

      - name: Test IPv6
        run: |
          ping6 -c 4 www.google.com || echo "ping6 failed."
          curl --ipv6 --max-time 10 https://www.google.com/ || echo "curl failed"
          sudo nc -l 12345 || echo "nc failed"
