name: Pull, build, push, test

on: [push]

jobs:

  pull_build_push:

    name: Pull, build, push
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:

      - name: Check out repository
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Try setting some annotations
        run: |
          echo "::debug file=app.js,line=1::Entered octocatAddition method"
          echo "::warning file=app.js,line=1,col=5::Missing semicolon"
          echo "::error file=app.js,line=10,col=15::Something went wrong"
