version: "3.7"

services:

    webapp-httpd:
        image: dockermediacloud/webapp-httpd:latest
        stop_signal: SIGKILL
        ports:
            # Expose to host for debugging
            - "8080:80"
        depends_on:
            - webapp-api

    webapp-api:
        image: dockermediacloud/webapp-api:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        expose:
            - "9090"
        depends_on:
            - postgresql-pgbouncer
            - solr-shard
            - rabbitmq-server
            - rescrape-media
            - word2vec-generate-snapshot-model
            # test_topics_api.t snapshots a topic
            - topics-snapshot
            # Multiple tests import Solr data
            - import-solr-data-for-testing

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        ports:
            # Publish port to host for debugging and PyCharm access
            - "127.0.0.1:6432:6432"
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    solr-shard:
        image: dockermediacloud/solr-shard:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        environment:
            MC_SOLR_SHARD_COUNT: "1"
        expose:
            - 8983
        depends_on:
            - solr-zookeeper

    solr-zookeeper:
        image: dockermediacloud/solr-zookeeper:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888

    rabbitmq-server:
        image: dockermediacloud/rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672

    rescrape-media:
        image: dockermediacloud/rescrape-media:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL

    word2vec-generate-snapshot-model:
        image: dockermediacloud/word2vec-generate-snapshot-model:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL

    topics-snapshot:
        image: dockermediacloud/topics-snapshot:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_TOPICS_SNAPSHOT_MODEL_REPS: "0"

    import-solr-data-for-testing:
        image: dockermediacloud/import-solr-data-for-testing:latest
        env_file: ./../global.env.dist
        environment:
            MC_SOLR_IMPORT_JOBS: 1
            MC_SOLR_IMPORT_MAX_QUEUED_STORIES: 100000
        stop_signal: SIGKILL
        depends_on:
            - postgresql-pgbouncer
            - solr-shard
