version: "3.7"

services:

    mc_webapp_httpd:
        image: dockermediacloud/mediacloud-webapp-httpd:latest
        stop_signal: SIGKILL
        ports:
            # Expose to host for debugging
            - "8080:80"
        depends_on:
            - mc_webapp_api

    mc_webapp_api:
        image: dockermediacloud/mediacloud-webapp-api:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        expose:
            - "9090"
        depends_on:
            - mc_postgresql_pgbouncer
            - mc_solr_shard
            - mc_rabbitmq_server
            - mc_rescrape_media
            - mc_word2vec_generate_snapshot_model
            # test_topics_api.t snapshots a topic
            - mc_topics_snapshot
            # Multiple tests import Solr data
            - mc_import_solr_data_for_testing

    mc_postgresql_pgbouncer:
        image: dockermediacloud/mediacloud-postgresql-pgbouncer:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - mc_postgresql_server

    mc_postgresql_server:
        image: dockermediacloud/mediacloud-postgresql-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5432

    mc_solr_shard:
        image: dockermediacloud/mediacloud-solr-shard:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        environment:
            MC_SOLR_SHARD_COUNT: "1"
        expose:
            - 8983
        depends_on:
            - mc_solr_zookeeper

    mc_solr_zookeeper:
        image: dockermediacloud/mediacloud-solr-zookeeper:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 2181
            - 2888
            - 3888

    mc_rabbitmq_server:
        image: dockermediacloud/mediacloud-rabbitmq-server:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672

    mc_rescrape_media:
        image: dockermediacloud/mediacloud-rescrape-media:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL

    mc_word2vec_generate_snapshot_model:
        image: dockermediacloud/mediacloud-word2vec-generate-snapshot-model:latest
        env_file: ./../global.env.dist
        stop_signal: SIGKILL

    mc_topics_snapshot:
        image: dockermediacloud/mediacloud-topics-snapshot:latest
        stop_signal: SIGKILL
        env_file: ./../global.env.dist
        environment:
            MC_TOPICS_SNAPSHOT_MODEL_REPS: "0"

    mc_import_solr_data_for_testing:
        image: dockermediacloud/mediacloud-import-solr-data-for-testing:latest
        env_file: ./../global.env.dist
        environment:
            MC_SOLR_IMPORT_JOBS: 1
            MC_SOLR_IMPORT_MAX_QUEUED_STORIES: 100000
        stop_signal: SIGKILL
        depends_on:
            - mc_postgresql_pgbouncer
            - mc_solr_shard
